---
- name: Ensure expected groups are created
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ k1599_users_present_groups|default([]) }}"

- name: Ensure expected groups are absent
  group:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ k1599_users_absent_groups|default([]) }}"

- name: Ensure expected users are created
  user:
    name: "{{ item.name }}"
    password: "{{ item.passwords.crypt }}"
    shell: '/bin/bash'
    groups: "{{ item.groups|default('users') }}"
    append: yes
    state: present
  with_items:
    - "{{ k1599_users_present_users }}"

- name: Ensure expected users are absend
  user:
    name: "{{ item  }}"
    state: absent
  with_items:
    - "{{ k1599_users_absent_users|default([]) }}"
