---
- name: restart_ssh
  service:
    name: ssh
    state: restarted
  tags:
    - service
    - ssh

- name: reload_ssh
  service:
    name: ssh
    state: restarted
  tags:
    - service
    - ssh
