---
- name: Lege SSH-Konfigdatei auf Server an.
  template:
    src: 'templates/sshd_config'
    dest: '/etc/ssh/sshd_config'
    owner: 'root'
    group: 'root'
    mode:  '0644'

- name: Lege Login-Banner mit Warnhinweis an.
  template:
    src: 'templates/issue.net'
    dest: '/etc/issue.net'
    owner: 'root'
    group: 'root'
    mode:  '0644'
