- name: restart_openvpn
  service:
    name: "{{ _openvpn_clt }}"
    state: restarted
  when: k1599_integration_test is not defined

- name: reload_openvpn
  service:
    name: "{{ _openvpn_clt }}"
    state: reloaded
  when: k1599_integration_test is not defined
