---
- include: asserts.yml

- name: Ensure rsyslog packages are present.
  package:
    name: "{{ item }}"
  with_items:
    - rsyslog
    - rsyslog-gnutls
    - rsyslog-doc
  tags:
    - packages
    - rsyslog

- name: Ensure remote config snippets at /etc/rsyslog.d/*.conf are present.
  template:
    dest: "/etc/rsyslog.d/{{ item }}"
    src: "etc/rsyslog.d/{{ item }}.j2"
    mode: "0664"
    owner: "{{ k1599_rsyslog_user }}"
    group: "{{ k1599_rsyslog_user_group }}"
  with_items:
    - 10_imtcp_template_remote_input.conf
    - 15_imtcp_rule_remote_input.conf
    - 30_imtcp_remote_input.conf
  notify: restart_rsyslog
  tags:
    - rsyslog

- name: Ensure directorys /var/{log,lib}/rsyslog is present.
  file:
    path: '{{ item }}'
    state: 'directory'
    mode: '0770'
    owner: "{{ k1599_rsyslog_user|default('root') }}"
    group: "{{ k1599_rsyslog_user_group|default('root') }}"
  notify: restart_rsyslog
  with_items:
    - '/var/lib/rsyslog'
    - "{{ k1599_rsyslog_destination_folder }}"
  tags:
    - rsyslog

- name: Ensure directory /etc/rsyslog.d/certs/ is present
  file:
    path: '/etc/rsyslog.d/certs/'
    state: 'directory'
  tags:
    - rsyslog

- name: Ensure /etc/rsyslog.d/certs/ca-chain.cert.pem is present
  template:
    src: 'etc/rsyslog.d/certs/ca-chain.cert.pem'
    dest: '/etc/rsyslog.d/certs/ca-chain.cert.pem'
    owner: 'root'
    group: 'root'
    mode: '0644'
  tags:
    - rsyslog

- name: Ensure /etc/rsyslog.d/certs/cert.pem is present
  copy:
    content: "{{ _vault_cert }}"
    dest: '/etc/rsyslog.d/certs/cert.pem'
    owner: 'root'
    group: 'root'
    mode: '0644'
  tags:
    - rsyslog

- name: Ensure /etc/rsyslog.d/certs/privkey.pem is present
  copy:
    content: "{{ _vault_cert_key }}"
    dest: '/etc/rsyslog.d/certs/privkey.pem'
    owner: "{{ k1599_rsyslog_user|default('root') }}"
    group: "{{ k1599_rsyslog_user_group|default('root') }}"
    mode: '0600'
  tags:
    - rsyslog

- name: Ensure that rsyslog is started
  service:
    name: rsyslog
    state: started
    enabled: yes
  tags:
    - service
    - rsyslog

- name: Ensure /etc/logrotate.d/rsyslog is present.
  template:
    dest: '/etc/logrotate.d/rsyslog'
    src: 'etc/logrotate.d/rsyslog.j2'
    mode: '0640'
    owner: 'root'
    group: 'root'
  tags:
    - rsyslog

- name: Ensure privilige drop is set to group adm
  lineinfile:
    dest: '/etc/rsyslog.conf'
    regexp: '^\$PrivDropToGroup .*'
    line: "$PrivDropToGroup {{ k1599_rsyslog_user_group }}"
    state: 'present'
  when: k1599_rsyslog_user_group != 'root'
  notify: restart_rsyslog
  tags:
    - service
    - rsyslog
