---
- name: Ensure common packages are installed
  package:
    name: "{{ item }}"
  with_items:
    - 'sudo'
    - 'python'
    - 'openssl'

- name: Disable IPV6 by copying sysctl.conf
  copy:
    src: 'templates/sysctl.conf'
    dest: '/etc/sysctl.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Ensure packages are absent
  apt: name={{ item }} state=absent
  with_items:
    - rsh-client
    - rsh-server
    - rsh-redone-client
    - rsh-redone-server
    - xserver-xorg

- name: Ensure hostname is set as expected
  hostname:
    name: "{{ fapra1599_common_hostname  }}"
