---
- name: Ensure common packages are present
  package:
    name: "{{ item }}"
  with_items:
    - "{{ k1599_common_present_packages }}"

- name: Ensure unwanted packages are absent
  package:
    name: "{{ item }}"
    state: 'absent'
  with_items:
    - "{{ k1599_common_absent_packages }}"

- name: Disable IPV6 by copying sysctl.conf
  copy:
    src: 'templates/sysctl.conf'
    dest: '/etc/sysctl.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Ensure hostname is set as expected
  hostname:
    name: "{{ fapra1599_common_hostname  }}"

- name: Ensure host entrys at /etc/hosts are present
  lineinfile:
    dest: '/etc/hosts'
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: 'present'
  when: hostvars[item].ansible_host is defined
  with_items:
    - "{{ groups['file_server'] }}"
