---
- set_fact:
    _nmb_srv: 'nmbd'
    _smb_srv: 'smbd'

- name: Ensure package samba is installed
  package:
    name: samba

- name: Create public dir
  file:
    path: "{{ k1599_file_server_public_share_path }}"
    state: directory
    mode: '0777'

- name: Ensure /etc/samba/smb.conf is present
  template:
    src: 'etc/samba/smb.conf.j2'
    dest: '/etc/samba/smb.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: restart_samba

- name: "Ensure service NetBIOS nameserver is stopped and disabled"
  service:
    name: "{{ _nmb_srv }}"
    state: stopped
    runlevel: '2 3 4 5'
    enabled: false

- name: "Ensure service samba is started and enabled: {{ k1599_file_server_smbd_enabled }}"
  service:
    name: "{{ _smb_srv }}"
    state: started
    runlevel: '2 3 4 5'
    enabled: "{{ k1599_file_server_smbd_enabled }}"

- name: Create Samba users if they don't exist yet or refresh their password
  shell: >
    (echo {{ item.0.passwords.plain }}; echo {{ item.0.passwords.plain }}) \
    | smbpasswd -s -a {{ item.0.name }}
  when: item.1.rc != 0 or refresh_users is defined
  register: create_user_output
  changed_when: "'Added user' in create_user_output.stdout"
  with_together:
    - "{{ k1599_users_present_users }}"
    - "{{ existing_users.results }}"
