---
- set_fact:
    _smb_srv: 'smbd'
    _clamav_srv: 'clamav-daemon'

- name: Ensure package samba is installed
  package:
    name: samba

- name: Ensure package clamav-daemon is installed
  package:
    name: clamav-daemon

- name: Create public dir
  file:
    path: "{{ k1599_file_server_public_share_path }}"
    state: directory
    mode: '0777'

- name: Ensure /etc/samba/smb.conf is present
  template:
    src: 'etc/samba/smb.conf.j2'
    dest: '/etc/samba/smb.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: restart_samba

- name: "Ensure service samba is started and enabled: {{ k1599_file_server_smbd_enabled }}"
  service:
    name: "{{ _smb_srv }}"
    state: started
    runlevel: '2 3 4 5'
    enabled: "{{ k1599_file_server_smbd_enabled }}"

- name: Create Samba users if they don't exist yet
  shell: >
    (pdbedit -L | grep {{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.name }}
  with_items: "{{ samba_users }}"
  register: create_user_output
  changed_when: "'Added user' in create_user_output.stdout"

- name: Ensure /etc/clamav/clamd.conf is present
  template:
    src: 'etc/clamav/clamd.conf.j2'
    dest: '/etc/clamav/clamd.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: restart_clamav

- name: "Ensure service clamav is started and enabled: {{ k1599_file_server_clamd_enabled }}"
  service:
    name: "{{ _clamav_srv }}"
    state: started
    runlevel: '2 3 4 5'
    enabled: "{{ k1599_file_server_clamd_enabled }}"
